package com.ssafy.fitbox.network.response

data class OrderResponse(
    val orderId: Long,
    val subscriptionGroupId: Long?,
    val userId: Int,
    val customerName: String? = null,
    val mealId: Long?,
    val mealName: String,
    val quantity: Int,
    val totalPrice: Int,
    val receiveType: String,
    val receiveDate: String?,
    val dateStart: String?,
    val dateEnd: String?,
    val mon: Long?,
    val tue: Long?,
    val wed: Long?,
    val thu: Long?,
    val fri: Long?,
    val sat: Long?,
    val sun: Long?,
    val storeId: Long?,
    val storeName: String?,
    val storeAddress: String?,
    val pickupPointId: Long? = null,
    val pickupPointName: String? = null,
    val pickupPointAddress: String? = null,
    val lockerNumber: String? = null,
    val address: String?,
    val orderStatus: String? = null,
    val paymentStatus: String?,
    val orderType: String,
    val subscriptionStatus: String?,
    val orderTime: String,
    val subscriptionItemsText: String?
)
